server: 
    port: 8080

spring: 
    datasource: 
        url: jdbc:mariadb://127.0.0.1:3306/study
        username: root
        password: root123!@#
        driver-class-name: org.mariadb.jdbc.Driver
    jpa: 
        show-sql: true
        generate-ddl: true
